name: Deploy President 2024 Serverless
on:
  push:
    branches:
      - develop_cicd
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
      - name: Push notification Telegram on start
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_THREAD_ID }}
        run: |
          UPPERCASE_TEXT=$(echo "${{ github.event.repository.name }}" | tr '[:lower:]' '[:upper:]')
          curl -s -X GET "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ vars.TELEGRAM_CHAT_ID }}" \
          -d "message_thread_id=${{ vars.TELEGRAM_THREAD_ID }}" \
          -d "parse_mode=HTML" \
          -d "text=<b>🟡 $UPPERCASE_TEXT IS DEPLOYING ON CLOUDFLARE WORKER</b>%0A%0A\
          <code>Environment:%20Development%0A\
          Branch:%20${{ github.ref_name }}%0A%0A\
          Commit:%20${{ env.COMMIT_MESSAGE }}%0A\
          Committer:%20${{ github.event.head_commit.committer.name }} (${{ github.event.head_commit.committer.email }})%0A\
          Commit url: ${{ github.event.head_commit.url }}%0A%0A\
          Date:%20${{ github.event.head_commit.timestamp }}%0A%0A\
          Bot ID: @president_2024_test_bot\
          </code>"
      - name: Build & Deploy President 2024 Serverless
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - name: Notify success
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_THREAD_ID }}
        run: |
          UPPERCASE_TEXT=$(echo "${{ github.event.repository.name }}" | tr '[:lower:]' '[:upper:]')
          curl -s -X GET "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ vars.TELEGRAM_CHAT_ID }}" \
          -d "message_thread_id=${{ vars.TELEGRAM_THREAD_ID }}" \
          -d "parse_mode=HTML" \
          -d "text=<b>✅ $UPPERCASE_TEXT DEPLOYED SUCCESSFULLY ON CLOUDFLARE WORKER</b>%0A%0A\
          <code>Environment:%20Development%0A\
          Branch:%20${{ github.ref_name }}%0A%0A\
          Commit:%20${{ env.COMMIT_MESSAGE }}%0A\
          Committer:%20${{ github.event.head_commit.committer.name }} (${{ github.event.head_commit.committer.email }})%0A\
          Commit url: ${{ github.event.head_commit.url }}%0A%0A\
          Date:%20${{ github.event.head_commit.timestamp }}%0A%0A\
          Bot ID: @president_2024_test_bot\
          </code>"
      - name: Notify failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ vars.TELEGRAM_THREAD_ID }}
        run: |
          UPPERCASE_TEXT=$(echo "${{ github.event.repository.name }}" | tr '[:lower:]' '[:upper:]')
          curl -s -X GET "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ vars.TELEGRAM_CHAT_ID }}" \
          -d "message_thread_id=${{ vars.TELEGRAM_THREAD_ID }}" \
          -d "parse_mode=HTML" \
          -d "text=<b>❌ $UPPERCASE_TEXT x DEPLOYMENT FAILED ON CLOUDFALRE WORKER</b>%0A%0A\
          <code>Environment:%20Development%0A\
          Branch:%20${{ github.ref_name }}%0A%0A\
          Commit:%20${{ env.COMMIT_MESSAGE }}%0A\
          Committer:%20${{ github.event.head_commit.committer.name }} (${{ github.event.head_commit.committer.email }})%0A\
          Commit url: ${{ github.event.head_commit.url }}%0A%0A\
          Date:%20${{ github.event.head_commit.timestamp }}%0A%0A\
          Bot ID: @president_2024_test_bot\
          </code>"
